export const LOCAL_MEMORY_MAX_ITEMS = 200;
export const LOCAL_MEMORY_COMPRESS_THRESHOLD = 160;
export const LOCAL_MEMORY_COMPRESS_HEAD = 80;
export const LOCAL_MEMORY_COMPRESS_MAX_LINES = 24;
export const LOCAL_MEMORY_COMPRESS_LINE_MAX_CHARS = 140;
export const LOCAL_MEMORY_SUMMARY_MAX_CHARS = 2400;

export const LOCAL_MEMORY_PERSIST_THROTTLE_MS = 280;
export const LOCAL_MEMORY_COMPRESS_SCHEDULE_MS = 700;
export const LOCAL_MEMORY_SERVER_FLUSH_DEBOUNCE_MS = 1600;
